### PR TITLE
Explicitly build URLs

### PR DESCRIPTION
**Pull request by kujenga**
This switches away from the `path.Join` building used for building URLs after some odd behavior was seen where malformed URLs were being created.

### CODE REVIEW

**Comment by kevindoyle** [comment]
Curious, what was coming out malformed?

**Comment by kujenga** [comment]
Example of the error: 

```
Post https:///api.postmarkapp.com/templates/validate: http: no Host in request URL
```

http://play.golang.org/p/9h-47srOvR shows different, but still incorrect behavior. This happens because `path.Join` cleans the path components, altering the preexisting slashes: https://golang.org/pkg/path/#Join

**Comment by kevindoyle** [comment]
Ooh because we were putting the scheme into something meant for paths :+1: Sorry about that!

**Comment by kujenga** [comment]
not at all!

**Comment by kevindoyle** [comment]
This looks good, ready to merge?

**Pull request merged**
